# Use an official Python runtime as a parent image
FROM python:3.12

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Copy the current directory contents into the container at /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt
COPY . /app

# Make port 8000 available to the world outside this container
EXPOSE 8001

# Define the command to run your application (replace with your actual command)
CMD python manage.py runserver 0.0.0.0:8001

