version: '3.12'

services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"  # Map host port 8001 to container port 8001
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]


  # FOR CONNECT TO THE MYSQL DATABASE
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: your_db_name
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"

  # FOR CONNECT TO THE POSTGRESQL DATABASE
  # db:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"