version: '3.8'

services:
    webapp:
        build:
            context: ../../
            dockerfile: infra-v4/local/Dockerfile.webapp
        command: >
            sh -c "pwd && ls &&
            python manage.py showmigrations &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn campusconnect.wsgi --bind 0.0.0.0:8007"
        volumes:
            - campusconnect-media:/data/media
            - campusconnect-static:/data/static
            - campusconnect-log:/data/log
        env_file:
            - ../../.env
        container_name: campusconnect_app
        ports:
            - "8007:8007"
    webserver:
        image: nginx:latest
        volumes:
            - campusconnect-media:/data/media
            - campusconnect-static:/data/static
            - campusconnect-log:/data/log
            - ./nginx.conf:/etc/nginx/nginx.conf            
        ports:
            - "80:80"
        container_name: campusconnect_server

volumes:
    campusconnect-media:
    campusconnect-static:
    campusconnect-log:
