# Generated by Django 3.2.16 on 2024-01-02 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mviewtracker_asseterror',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='timestamp of page visit')),
                ('url', models.CharField(max_length=2000)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('method', models.CharField(max_length=20)),
                ('http_user_agent', models.CharField(blank=True, max_length=2000, null=True)),
                ('http_referer', models.CharField(blank=True, max_length=2000, null=True)),
                ('query_string', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_host', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_count', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SQLReporting',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mviewtracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='timestamp of page visit')),
                ('url', models.CharField(max_length=2000)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('method', models.CharField(max_length=20)),
                ('http_user_agent', models.CharField(blank=True, max_length=2000, null=True)),
                ('http_referer', models.CharField(blank=True, max_length=2000, null=True)),
                ('query_string', models.CharField(blank=True, max_length=2000, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_host', models.CharField(blank=True, max_length=2000, null=True)),
                ('owner_uniqid', models.CharField(blank=True, max_length=100, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Browse History',
            },
        ),
    ]
