# Generated by Django 3.2.16 on 2024-01-02 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_JD_1', models.CharField(blank=True, help_text='Target Job Description', max_length=5000, null=True)),
                ('target_JD_2', models.CharField(blank=True, help_text='Target Job Description', max_length=5000, null=True)),
                ('ques_details', models.CharField(blank=True, max_length=3000, null=True)),
                ('why_needed', models.CharField(choices=[('cd01', 'Didnot Find this serv in exp180'), ('cd02', 'I donotk now where to search'), ('cd03', 'it was time consuming to search for this')], default='no', max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('resume', models.FileField(default='null', upload_to='adhoc_resumes/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Adhoc Requests',
            },
        ),
        migrations.CreateModel(
            name='mamar_pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(blank=True, max_length=500, null=True)),
                ('amarpay_payment_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uniqid', models.CharField(max_length=100)),
                ('title', models.CharField(default='mcart title value Not Set', max_length=500)),
                ('sku', models.CharField(max_length=6)),
                ('removed', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('resume_required', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('tracking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(max_length=50)),
                ('item_id', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='this is the sale price at the time.', max_digits=1000)),
                ('coupon_subtract', models.DecimalField(decimal_places=2, default=0, help_text='this is the amount subtracted from base price due to coupons.', max_digits=1000)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, help_text='this is the final price after discounts.', max_digits=1000)),
                ('tax_price', models.DecimalField(decimal_places=2, default=0, help_text='this is the tax that will be calculated on this mcart item.', max_digits=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
        ),
        migrations.CreateModel(
            name='mcompleted_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypaltransaction_id', models.CharField(default='', max_length=100)),
                ('payer_id', models.CharField(default='', max_length=100)),
                ('capture_id', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email_address', models.CharField(default='', max_length=1000)),
                ('guest_login_email_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
        ),
        migrations.CreateModel(
            name='mcompleted_refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypalrefund_id', models.CharField(max_length=100)),
                ('amount_currencycode', models.CharField(max_length=5)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('r01', 'Reason #1'), ('r02', 'Reason #2'), ('r03', 'Reason #3'), ('r04', 'Reason #4'), ('r05', 'Reason #5'), ('r06', 'Reason #6')], default='r01', max_length=5)),
                ('explanation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
        ),
        migrations.CreateModel(
            name='mprod_posti20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '04-PostI20-Services',
            },
        ),
        migrations.CreateModel(
            name='mprod_posti20_catlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '04-PostI20_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_prei20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '05-Prei20',
            },
        ),
        migrations.CreateModel(
            name='mprod_prei20_catlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '05_Prei20_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '09-Strategy-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_strategy_taglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(default='job search', max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '09_Strategy_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_univcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '07-Univcom-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_univcom_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '07_Univcom_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_visaassist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('saleprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('golivestatus', models.CharField(choices=[('active', 'Live'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('trending', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('homepage_showup', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
            ],
            options={
                'verbose_name_plural': '03-Visaassist-services',
            },
        ),
        migrations.CreateModel(
            name='mprod_visaassist_catlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(default='regular', max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': '03_Visaassist_Cat_List',
            },
        ),
        migrations.CreateModel(
            name='msku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threeletterprefix', models.CharField(max_length=3)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'msku Services',
            },
        ),
        migrations.CreateModel(
            name='mssl_commerz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(blank=True, max_length=500, null=True)),
                ('ssl_payment_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='muniqueid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uniqid', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('muser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mprod_visaassist_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_visaassist')),
            ],
            options={
                'verbose_name_plural': '03_Visaassist_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_visaassist_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='inventory.mprod_visaassist')),
            ],
            options={
                'verbose_name_plural': '03_Visaassist_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_visaassist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_visaassist_catlist'),
        ),
        migrations.CreateModel(
            name='mprod_univcom_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_univcom')),
            ],
            options={
                'verbose_name_plural': '07_Univcom_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_univcom_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='inventory.mprod_univcom')),
            ],
            options={
                'verbose_name_plural': '07_Univcom_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_univcom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_univcom_list'),
        ),
        migrations.CreateModel(
            name='mprod_strategy_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_strategy')),
            ],
            options={
                'verbose_name_plural': '09_Strategy_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_strategy_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='inventory.mprod_strategy')),
            ],
            options={
                'verbose_name_plural': '09_Strategy_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_strategy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_strategy_taglist'),
        ),
        migrations.CreateModel(
            name='mprod_prei20_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_prei20')),
            ],
            options={
                'verbose_name_plural': '05_Prei20_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_prei20_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='inventory.mprod_prei20')),
            ],
            options={
                'verbose_name_plural': '05_Prei20_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_prei20',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_prei20_catlist'),
        ),
        migrations.CreateModel(
            name='mprod_posti20_serviceoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_posti20')),
            ],
            options={
                'verbose_name_plural': '04-PostI20_ServOption_Serv_List',
            },
        ),
        migrations.CreateModel(
            name='mprod_posti20_deliveryoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=2000)),
                ('listprice', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.99, max_digits=1000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('products', models.ManyToManyField(to='inventory.mprod_posti20')),
            ],
            options={
                'verbose_name_plural': '04-PostI20_DelivOption_List',
            },
        ),
        migrations.AddField(
            model_name='mprod_posti20',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mprod_posti20_catlist'),
        ),
        migrations.CreateModel(
            name='mcart_serviceoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Set', max_length=500)),
                ('sku', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='price', max_digits=1000)),
                ('serviceoption_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('mcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.mcart')),
            ],
        ),
        migrations.CreateModel(
            name='mcart_fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uniqid', models.CharField(max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('document', models.FileField(upload_to=inventory.models.mcart_uploadpath())),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_failed_id', models.IntegerField(default=0)),
                ('mcompleted_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mcompleted_purchase')),
            ],
        ),
        migrations.CreateModel(
            name='mcart_deliveryoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Set', max_length=100)),
                ('sku', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='price', max_digits=1000)),
                ('hours_to_cancel_after_payment', models.IntegerField(default=168)),
                ('hours_to_deliver_after_payment', models.IntegerField(default=336)),
                ('deliveryoption_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('mcart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.mcart')),
            ],
        ),
        migrations.CreateModel(
            name='mcart_coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('mcart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.mcart')),
                ('mcoupon_given', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.mcoupon_given')),
            ],
        ),
        migrations.AddField(
            model_name='mcart',
            name='mcompleted_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mcompleted_purchase'),
        ),
        migrations.AddField(
            model_name='mcart',
            name='mcompleted_refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mcompleted_refund'),
        ),
        migrations.AddField(
            model_name='mcart',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
