# Generated by Django 3.2.16 on 2024-01-02 05:59

from django.db import migrations, models
import django.db.models.deletion
import guestactions.models.guest_resume_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('msg', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='GuestResumeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to=guestactions.models.guest_resume_upload.guest_resume_location)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume Files by Guest',
                'verbose_name_plural': 'Resume Files by Guest',
            },
        ),
        migrations.CreateModel(
            name='InviteFriendsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_last_name', models.CharField(max_length=100)),
                ('guest_email_address', models.CharField(max_length=100)),
                ('friend_first_name', models.CharField(max_length=100)),
                ('friend_email_address', models.CharField(max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
            options={
                'verbose_name_plural': 'Invite Friend List',
            },
        ),
        migrations.CreateModel(
            name='mcoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_liked', models.CharField(choices=[('mprod_prei20', 'PreI-20'), ('mprod_visaassist', 'Visaassist'), ('mprod_univcom', 'Univcom'), ('mprod_posti20', 'PostI-20'), ('mprod_rolebased', 'Identity'), ('mprod_strategy', 'Strategy'), ('mprod_visabased', 'Bandwidth'), ('mprod_xyz', 'General'), ('mprod_adhoc', 'Adhoc'), ('mprod_referral', 'Referral')], default='mprod_exp180', max_length=20)),
                ('discount_percent', models.IntegerField(default=1)),
                ('hours_to_expire', models.IntegerField(default=336)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
            ],
            options={
                'verbose_name_plural': 'Coupon Supported Product List',
            },
        ),
        migrations.CreateModel(
            name='mfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=1000)),
                ('product_liked', models.CharField(choices=[('mprod_prei20', 'PreI-20'), ('mprod_visaassist', 'Visaassist'), ('mprod_univcom', 'Univcom'), ('mprod_posti20', 'PostI-20'), ('mprod_rolebased', 'Identity'), ('mprod_strategy', 'Strategy'), ('mprod_visabased', 'Bandwidth'), ('mprod_xyz', 'General'), ('mprod_adhoc', 'Adhoc'), ('mprod_referral', 'Referral')], default='mprod_exp180', max_length=24)),
                ('feedback', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='SiteSurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_used', models.CharField(blank=True, max_length=100, null=True)),
                ('hmpg_design', models.CharField(blank=True, max_length=100, null=True)),
                ('userfriendly', models.CharField(blank=True, max_length=100, null=True)),
                ('promo_offers', models.CharField(blank=True, max_length=100, null=True)),
                ('service_lineup', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('recommend', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation site survey')),
            ],
        ),
        migrations.CreateModel(
            name='mcoupon_given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string_32', models.CharField(max_length=33)),
                ('expired', models.BooleanField(default=False)),
                ('usedinpurchase', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('mcoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestactions.mcoupon')),
            ],
            options={
                'verbose_name_plural': 'CouponCode List',
            },
        ),
    ]
