# Generated by Django 3.2.16 on 2024-01-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerListGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('reguser', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default='00000000000', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
            ],
            options={
                'verbose_name': 'Buyer Email List',
                'verbose_name_plural': 'Buyer Email List',
            },
        ),
        migrations.CreateModel(
            name='mcoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_liked', models.CharField(choices=[('mprod_prei20', 'PreI-20'), ('mprod_visaassist', 'Visaassist'), ('mprod_univcom', 'Univcom'), ('mprod_posti20', 'PostI-20'), ('mprod_rolebased', 'Identity'), ('mprod_strategy', 'Strategy'), ('mprod_visabased', 'Bandwidth'), ('mprod_xyz', 'General'), ('mprod_adhoc', 'Adhoc'), ('mprod_referral', 'Referral')], default='mprod_prei20', max_length=20)),
                ('discount_percent', models.IntegerField(default=1)),
                ('hours_to_expire', models.IntegerField(default=336)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
            ],
            options={
                'verbose_name_plural': 'Coupon Supported Product List',
            },
        ),
        migrations.CreateModel(
            name='mcoupon_given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string_32', models.CharField(max_length=33)),
                ('expired', models.BooleanField(default=False)),
                ('usedinpurchase', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('mcoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.mcoupon')),
            ],
            options={
                'verbose_name_plural': 'Coupon Code List',
            },
        ),
    ]
