# Generated by Django 3.2.16 on 2024-01-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msendmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=1000)),
                ('plain_message', models.TextField()),
                ('html_message', models.TextField()),
                ('from_email', models.CharField(default='', max_length=1000)),
                ('to_emails', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('sent_successfully', models.BooleanField(default=False)),
                ('appname', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='msendmail_failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('recipient_string', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='timestamp of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='timestamp of last update')),
                ('msendmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymailroom.msendmail')),
            ],
        ),
    ]
